name: dart_web3_core
description: dart_web3_core - a web3 library for dart for interaction with ethereum
  nodes using HTTP or WebSocket. Supports custom credentials providers like
  WalletConnect and Metamask.
version: 2.5.19
homepage: https://starkleytech.com
repository: https://github.com/starkleytech/dart_web3_core

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^2.4.1
  build_config: ^1.1.1
  built_collection: ^5.1.1
  code_builder: ^4.5.0
  collection: ^1.16.0
  convert: ^3.1.1
  dart_style: ^2.3.2
  http: ^1.3.0
  js: ^0.7.2
  json_rpc_2: ^3.0.3
  meta: ^1.16.0
  path: ^1.9.1
  pointycastle: ^4.0.0
  stream_channel: ^2.1.4
  stream_transform: ^2.1.1
  typed_data: ^1.4.0
  universal_html: ^2.2.4
  uuid: ^4.5.1

dev_dependencies:
  async: ^2.11.0
  build_runner: ^2.4.6
  build_test: ^2.2.0
  coverage: ^1.6.3
  test: ^1.24.6
  web_socket_channel: ^3.0.2
